 

 export const metal = [
    {
     img2:'./img/img 1.svg',
     img3:"./img/like.svg",
     img4:"./img/icon_bed.svg",
     name1: 'Новая сосновка',
     brand: "5 спальных мест",
     img5:"./img/icon_entertainment.svg",
     height: "Настольный теннис",
     img6:"./img/Vector 6 (Stroke).svg",
     grand: "Баня",
     img7:"./img/icon_waterpool.svg",
     num: "Бассейн",
     color: "от 10 000 ₽ / сутки ",
     valie:"Подробнее",
   },
   {
     img2:'./img/img 2.svg',
     img3:"./img/like.svg",
     img4:"./img/icon_bed.svg",
     name1: 'Новая сосновка',
     brand: "5 спальных мест",
     img5:"./img/icon_entertainment.svg",
     height: "Настольный теннис",
     img6:"./img/Vector 6 (Stroke).svg",
     grand: "Баня",
     img7:"./img/icon_waterpool.svg",
     num: "Бассейн",
     color: "от 10 000 ₽ / сутки ",
     valie:"Подробнее",
   },
   {
     img2:'./img/img 3.svg',
     img3:"./img/like.svg",
     img4:"./img/icon_bed.svg",
     name1: 'Новая сосновка',
     brand: "5 спальных мест",
     img5:"./img/icon_entertainment.svg",
     height: "Настольный теннис",
     img6:"./img/Vector 6 (Stroke).svg",
     grand: "Баня",
     img7:"./img/icon_waterpool.svg",
     num: "Бассейн",
     color: "от 10 000 ₽ / сутки ",
     valie:"Подробнее",
   },
   {
     img2:'./img/img 4.svg',
     img3:"./img/like.svg",
     img4:"./img/icon_bed.svg",
     name1: 'Новая сосновка',
     brand: "5 спальных мест",
     img5:"./img/icon_entertainment.svg",
     height: "Настольный теннис",
     img6:"./img/Vector 6 (Stroke).svg",
     grand: "Баня",
     img7:"./img/icon_waterpool.svg",
     num: "Бассейн",
     color: "от 10 000 ₽ / сутки ",
     valie:"Подробнее",
   },
   {
     img2:'./img/img 5.svg',
     img3:"./img/like.svg",
     img4:"./img/icon_bed.svg",
     name1: 'Новая сосновка',
     brand: "5 спальных мест",
     img5:"./img/icon_entertainment.svg",
     height: "Настольный теннис",
     img6:"./img/Vector 6 (Stroke).svg",
     grand: "Баня",
     img7:"./img/icon_waterpool.svg",
     num: "Бассейн",
     color: "от 8500 ₽ / сутки ",
     valie:"Подробнее",
   },
   {
     img2:'./img/img 6.svg',
     img3:"./img/like.svg",
     img4:"./img/icon_bed.svg",
     name1: 'Новая сосновка',
     brand: "5 спальных мест",
     img5:"./img/icon_entertainment.svg",
     height: "Настольный теннис",
     img6:"./img/Vector 6 (Stroke).svg",
     grand: "Баня",
     img7:"./img/icon_waterpool.svg",
     num: "Бассейн",
     color: "от  4000 ₽ / сутки ",
     valie:"Подробнее",
   },
   ];

   export const prof = [
    {
        imgg:'./img/buffet 1.svg',
        name2: 'Кейтеринг',
    },
    {
        imgg:'./img/chef (Traced).png',
        name2: 'Выездной повар',
    },
    {
        imgg:'./img/cocktail 1 (Traced).png',
        name2: 'Фуршет',
    },
    {
        imgg:'./img/confetti (Traced).svg',
        name2: 'Шоу программа',
    },
    {
        imgg:'./img/Frame 14 (Traced).svg',
        name2: 'Трансфер',
    },
    {
        imgg:'./img/microphone (Traced).svg',
        name2: 'Мероприятия под ключ',
    },

   ];

   export const krov = [
    {
        img9:'./img/k1.svg',
        name9: 'Работаем с юридическими <br> и физическими лицами ',
    },
    {
        img9:'./img/k2.svg',
        name9: 'Бесплатный подбор, честные <br> консультации и открытость <br> к сотрудничеству',
    },
    {
        img9:'./img/k3.svg',
        name9: 'Работаем с 2014 года. Консультируем <br> 30-80 человек в сутки, заселяем от 3 <br> до 5 компаний в день. Помогли более <br> 21 000 клиентам ',
    },
    {
        img9:'./img/k 4.svg',
        name9: 'Средний рейтинг компании 4,5 <br> из 5 (Avito, Google, Отзовик) ',
    },
  ];